INPUT_EMAIL_HEIGHT = 250
INPUT_HEADER_HEIGHT = 170
COMPACT_INPUT_EMAIL_HEIGHT = 120
COMPACT_INPUT_HEADER_HEIGHT = 90
RESULT_HEADER_COLS = [6, 1]
TOP_SECTION_COLS = [2.2, 1]
BOTTOM_SECTION_COLS = [1.0, 1.4, 0.9]

SECOND_ROW_MIN_HEIGHT = 228
SECOND_ROW_MAX_HEIGHT = 320
SECOND_ROW_BOTTOM_PADDING = 14
NEXT_STEP_BASE_HEIGHT = 76
NEXT_STEP_LINE_HEIGHT = 20
NEXT_STEP_WRAP_CHARS = 58
TICKET_SUMMARY_PANEL_HEIGHT = 232
PARSED_COLLAPSED_HEIGHT = 96
PARSED_EXPANDED_HEIGHT = 160

ANALYZE_INFO_TEXT = "Please paste an email below to check for phishing signs and get clear guidance on what to do next."
AI_NOT_READY_TEXT = "AI explanation has not generated yet."
PARSED_DETAILS_TOGGLE_KEY = "show_parsed_details"

RULES_PER_ROW = 2
MAX_TOP_REASONS = 4
MAX_FACT_DOMAINS = 3
MAX_FACT_PHRASES = 4
MAX_RULE_EVIDENCE = 3
MISMATCH_RULE_ID = "from_reply_to_mismatch"
FACTS_COLUMN_WIDTHS = [1.55, 1.05]